"use client";

import { useState, useEffect, useRef } from 'react';
import Link from 'next/link';
import { ArrowLeft, Search, Filter, Plus, Minus, Save, Package, QrCode, X } from 'lucide-react';
import { getItems, updateItemQuantity, Item } from '@/lib/firebase';
import { Html5Qrcode } from 'html5-qrcode';

export default function PickerPanel() {
  const [items, setItems] = useState<Item[]>([]);
  const [filteredItems, setFilteredItems] = useState<Item[]>([]);
  const [loading, setLoading] = useState(true);

  const [searchQuery, setSearchQuery] = useState('');

  const [editingQuantity, setEditingQuantity] = useState<{ [id: string]: number }>({});
  const [savingId, setSavingId] = useState<string | null>(null);
  const [expandedItemId, setExpandedItemId] = useState<string | null>(null);

  const toggleExpand = (id: string | undefined) => {
    if (!id) return;
    setExpandedItemId(prev => prev === id ? null : id);
  };

  // QR Scanner State
  const [isScanning, setIsScanning] = useState(false);
  const [scannedItem, setScannedItem] = useState<Item | null>(null);
  const scannerRef = useRef<Html5Qrcode | null>(null);

  useEffect(() => {
    fetchItems();
  }, []);

  const fetchItems = async () => {
    setLoading(true);
    try {
      const data = await getItems();
      setItems(data);
      setFilteredItems(data);

      const initialQtys: { [id: string]: number } = {};
      data.forEach(item => {
        if (item.id) initialQtys[item.id] = item.quantity;
      });
      setEditingQuantity(initialQtys);
    } catch (error) {
      console.error("Error fetching items", error);
    }
    setLoading(false);
  };

  useEffect(() => {
    let result = items;
    if (searchQuery) {
      const lowerQuery = searchQuery.toLowerCase();
      result = result.filter(item =>
        item.name.toLowerCase().includes(lowerQuery) ||
        item.sku.toLowerCase().includes(lowerQuery)
      );
    }
    setFilteredItems(result);
  }, [searchQuery, items]);

  // QR Scanner Logic
  useEffect(() => {
    if (isScanning) {
      const scanner = new Html5Qrcode("qr-reader");
      scannerRef.current = scanner;

      scanner.start(
        { facingMode: "environment" },
        { fps: 10, qrbox: { width: 250, height: 250 } },
        (decodedText) => {
          try {
            const data = JSON.parse(decodedText);
            const foundItem = items.find(i => i.id === data.id || i.sku === data.sku);
            if (foundItem) {
              setScannedItem(foundItem);
              setSearchQuery(foundItem.sku); // Also filter the list
              stopScanning();
            } else {
              alert("Scanned item not found in inventory!");
            }
          } catch (e) {
            console.error("Invalid QR Code", e);
            alert("Invalid QR Code Format. Make sure it was generated by the Admin Panel.");
          }
        },
        (errorMessage) => {
          // parse errors are frequent, ignore them
        }
      ).catch(err => {
        console.error("Error starting scanner", err);
        alert("Failed to start camera. Please check permissions.");
        setIsScanning(false);
      });
    } else {
      stopScanning();
    }

    return () => {
      stopScanning();
    };
  }, [isScanning, items]);

  const stopScanning = () => {
    if (scannerRef.current) {
      if (scannerRef.current.isScanning) {
        scannerRef.current.stop().catch(console.error);
      }
      scannerRef.current.clear();
      scannerRef.current = null;
    }
    setIsScanning(false);
  };

  const handleQuantityChange = (id: string, delta: number) => {
    setEditingQuantity(prev => {
      const current = prev[id] || 0;
      const next = Math.max(0, current + delta);
      return { ...prev, [id]: next };
    });
  };

  const handleManualQuantityChange = (id: string, value: string) => {
    const num = parseInt(value);
    if (!isNaN(num) && num >= 0) {
      setEditingQuantity(prev => ({ ...prev, [id]: num }));
    }
  };

  const saveQuantity = async (id: string) => {
    setSavingId(id);
    try {
      const newQty = editingQuantity[id];
      const itemToUpdate = items.find(i => i.id === id);

      if (itemToUpdate) {
        await updateItemQuantity(id, newQty, {
          name: itemToUpdate.name,
          sku: itemToUpdate.sku,
          oldQuantity: itemToUpdate.quantity,
          location: itemToUpdate.location,
          rack: itemToUpdate.rack,
          row: itemToUpdate.row,
          position: itemToUpdate.position
        });
      } else {
        await updateItemQuantity(id, newQty);
      }

      // Update local state
      setItems(prev => prev.map(item => item.id === id ? { ...item, quantity: newQty } : item));

      // If scanned item modal is open, update it
      if (scannedItem && scannedItem.id === id) {
        setScannedItem({ ...scannedItem, quantity: newQty });
      }
    } catch (error) {
      console.error('Error saving quantity', error);
    }
    setSavingId(null);
  };

  const renderItemCard = (item: Item, isModal: boolean = false) => {
    const isExpanded = isModal || expandedItemId === item.id;

    return (
      <div
        key={item.id}
        className="card"
        style={{ display: 'flex', flexDirection: 'column', padding: '1.5rem', width: '100%', marginBottom: isModal ? '0' : '1.5rem', cursor: isModal ? 'default' : 'pointer' }}
        onClick={() => !isModal && toggleExpand(item.id)}
      >
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '1rem' }}>
          <div>
            <h3 style={{ fontSize: '1.25rem', fontWeight: '600', color: 'var(--primary)', marginBottom: '0.25rem' }}>{item.name}</h3>
            <span style={{ fontSize: '0.875rem', color: 'var(--text-muted)' }}>{item.sku}</span>
          </div>
        </div>

        <div style={{ fontSize: '0.875rem', marginBottom: '1.5rem', flex: '1' }}>
          <strong>Location:</strong> {item.location}
        </div>

        {isExpanded && (
          <div className="animate-fade-in" style={{ fontSize: '0.875rem', marginBottom: '1.5rem', padding: '1rem', backgroundColor: 'var(--background)', borderRadius: 'var(--radius-md)', border: '1px solid var(--border)' }} onClick={(e) => e.stopPropagation()}>
            <h4 style={{ marginBottom: '0.75rem', color: 'var(--text-muted)', fontSize: '0.75rem', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Material Details</h4>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.75rem' }}>
              <div><span style={{ color: 'var(--text-muted)' }}>Size:</span> {item.size || '-'}</div>
              <div><span style={{ color: 'var(--text-muted)' }}>Colour:</span> {item.colour || '-'}</div>
              <div><span style={{ color: 'var(--text-muted)' }}>UPPS:</span> {item.upps || '-'}</div>
              <div><span style={{ color: 'var(--text-muted)' }}>CORE:</span> {item.core || '-'}</div>
              <div><span style={{ color: 'var(--text-muted)' }}>Rack:</span> {item.rack || '-'}</div>
              <div><span style={{ color: 'var(--text-muted)' }}>Row:</span> {item.row || '-'}</div>
              <div><span style={{ color: 'var(--text-muted)' }}>Position:</span> {item.position || '-'}</div>
            </div>
          </div>
        )}

        <div style={{ borderTop: '1px solid var(--border)', paddingTop: '1.5rem', display: 'flex', flexDirection: 'column', gap: '1rem' }} onClick={(e) => e.stopPropagation()}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
            <span style={{ fontWeight: '500' }}>Quantity:</span>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', background: 'var(--background)', padding: '0.25rem', borderRadius: 'var(--radius-sm)' }}>
              <button className="btn-icon" onClick={() => item.id && handleQuantityChange(item.id, -1)} style={{ padding: '0.25rem' }}>
                <Minus size={16} />
              </button>
              <input
                type="number"
                min="0"
                className="input-field"
                style={{ width: '60px', padding: '0.25rem', textAlign: 'center', border: 'none', background: 'transparent' }}
                value={item.id ? editingQuantity[item.id] ?? item.quantity : 0}
                onChange={(e) => item.id && handleManualQuantityChange(item.id, e.target.value)}
              />
              <button className="btn-icon" onClick={() => item.id && handleQuantityChange(item.id, 1)} style={{ padding: '0.25rem' }}>
                <Plus size={16} />
              </button>
            </div>
          </div>

          {item.id && editingQuantity[item.id] !== item.quantity && (
            <button
              className="btn btn-primary animate-fade-in"
              style={{ width: '100%', justifyContent: 'center' }}
              onClick={() => {
                if (item.id) saveQuantity(item.id);
              }}
              disabled={savingId === item.id}
            >
              <Save size={18} /> {savingId === item.id ? 'Saving...' : 'Save Updates'}
            </button>
          )}
        </div>
      </div>
    );
  };

  return (
    <div className="container animate-fade-in">
      <div className="header">
        <div>
          <Link href="/" className="btn-icon" style={{ display: 'inline-block', marginBottom: '1rem' }}>
            <ArrowLeft size={20} />
          </Link>
          <h1 className="header-title">Picker Operations</h1>
        </div>
        <button className="btn btn-primary" onClick={() => setIsScanning(true)}>
          <QrCode size={20} /> Scan QR Code
        </button>
      </div>

      {/* Filters Area */}
      <div className="card" style={{ marginBottom: '2rem', display: 'flex', gap: '1.5rem', flexWrap: 'wrap', alignItems: 'center' }}>
        <div style={{ flex: '1', minWidth: '250px', position: 'relative' }}>
          <Search size={20} style={{ position: 'absolute', left: '1rem', top: '50%', transform: 'translateY(-50%)', color: 'var(--text-muted)' }} />
          <input
            className="input-field"
            style={{ width: '100%', paddingLeft: '3rem' }}
            placeholder="Search by name or SKU..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
          />
        </div>
      </div>

      {/* Grid of Items */}
      {loading ? (
        <div className="empty-state">Loading materials...</div>
      ) : filteredItems.length === 0 ? (
        <div className="empty-state">
          <Package size={48} style={{ margin: '0 auto 1rem', opacity: 0.5 }} />
          No items match your search.
        </div>
      ) : (
        <div className="data-grid">
          {filteredItems.map(item => renderItemCard(item))}
        </div>
      )}

      {/* Scanner Modal */}
      {isScanning && (
        <div className="modal-overlay">
          <div className="modal-content">
            <div className="modal-header">
              <h2 className="modal-title">Scan QR Code</h2>
              <button className="modal-close" onClick={() => setIsScanning(false)}><X size={24} /></button>
            </div>
            <div id="qr-reader" style={{ width: '100%', maxWidth: '400px', margin: '0 auto', overflow: 'hidden', borderRadius: 'var(--radius-md)' }}></div>
            <p style={{ textAlign: 'center', marginTop: '1rem', color: 'var(--text-muted)' }}>
              Point your camera at an item's QR code to scan.
            </p>
          </div>
        </div>
      )}

      {/* Scanned Item Modal */}
      {scannedItem && !isScanning && (
        <div className="modal-overlay">
          <div className="modal-content" style={{ padding: '0', background: 'transparent', border: 'none', boxShadow: 'none' }}>
            <div style={{ display: 'flex', justifyContent: 'flex-end', paddingBottom: '0.5rem' }}>
              <button className="btn-icon" onClick={() => setScannedItem(null)} style={{ background: 'var(--surface)', border: '1px solid var(--border)' }}>
                <X size={24} />
              </button>
            </div>
            {renderItemCard(scannedItem, true)}
          </div>
        </div>
      )}
    </div>
  );
}
